name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          sudo apt-get install pandoc
          bazel test --sandbox_debug //...
          bazel build --sandbox_debug questions/...
